---
image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build
  - push
  - test

before_script:
  - docker info

build_docker_image:
  stage: build
  script:
    - docker build -f Dockerfile-debian10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:buster .
    - docker build -f Dockerfile-debiansid -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:sid -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:unstable .

push_to_registries:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker build -f Dockerfile-debiansid -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:unstable .
   - docker build -f Dockerfile-debian10 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:10 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:buster -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest .
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:unstable
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:10
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:buster
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest

test_docker_images:
  stage: test
  script:
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid shellcheck --version
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:buster shellcheck --version
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest shellcheck --version
