---
image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # https://gitlab.com/gitlab-org/gitlab-ce/issues/64959
  # 19.03 had some breaking changes compared to 18.09
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - docker info

build_d10:
  stage: build
  script:
    - docker build --rm -f Dockerfile-debian10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:buster .

build_dsid:
  stage: build
  script:
    - docker build --rm -f Dockerfile-debiansid -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:sid -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:unstable .

push_dsid_dockerhub:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker build --rm -f Dockerfile-debiansid -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:unstable .
   - docker images
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:unstable

push_d10_dockerhub:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker build --rm -f Dockerfile-debian10 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:10 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:buster -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest .
   - docker images
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:10
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:buster
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest

push_dsid_to_gitlab_reg:
 stage: push
 only:
   - master
 script:
   - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
   - docker build --rm -f Dockerfile-debiansid -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:sid -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:unstable .
   - docker images
   - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:sid
   - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:unstable

push_d10_to_gitlab_reg:
 stage: push
 only:
   - master
 script:
   - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
   - docker build --rm -f Dockerfile-debian10 -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:10 -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:buster -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest .
   - docker images
   - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:10
   - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:buster
   - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest