---
#image: qwe1/debdocker:20.10
image: crazymax/docker:latest
services:
  - name: docker:20.10-dind
    command: ["--experimental"]

variables:
  # for some reason docker on gitlab throws context erros with these enabled
  #DOCKER_HOST: tcp://docker:2376
  #DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  #DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  #BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64

before_script:
  - mkdir -p $HOME/.docker/cli-plugins/
  - docker buildx version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
  # https://gitlab.com/richardskumat/playground/-/jobs/2762899800
  - docker context create whatever
  - docker buildx create whatever
  ##
  - docker buildx create --use --driver docker-container --name whatever --platform=linux/amd64,linux/arm/v7,linux/arm64
  - docker buildx inspect --bootstrap whatever
  - docker buildx ls
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

stages:
  - build
  - push
  - test

build:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    # - docker buildx build --push -t qwe1/playground:latest -t qwe1/playground:$CI_COMMIT_SHORT_SHA -f Dockerfile --platform linux/amd64,linux/arm/v7,linux/arm64 .
    - docker buildx build --load -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHORT_SHA -f Dockerfile-debian11 --platform linux/amd64 .
    - docker buildx build --load -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHORT_SHA-sid -f Dockerfile-debiansid --platform linux/amd64 .
    - docker buildx build --load -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHORT_SHA-alpine -f Dockerfile-alpine --platform linux/amd64 .
    - docker images
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHORT_SHA shellcheck --version
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHORT_SHA-sid shellcheck --version
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHORT_SHA-alpine shellcheck --version

push_to_registries:
 stage: push
 only:
   - master
 script:
   - docker buildx build --push -f Dockerfile-debiansid -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:unstable --platform linux/amd64,linux/arm/v7,linux/arm64 .
   - docker buildx build --push -f Dockerfile-debian11 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:11 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:bullseye -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest --platform linux/amd64,linux/arm/v7,linux/arm64 .
   - docker buildx build --push -f Dockerfile-alpine -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:alpine --platform linux/amd64,linux/arm/v7,linux/arm64 .
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:11 shellcheck --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid shellcheck --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:alpine shellcheck --version

test_docker_images:
  stage: test
  script:
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid shellcheck --version
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:bullseye shellcheck --version
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest shellcheck --version
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:alpine shellcheck --version
