---
image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build_d10:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build --rm -f Dockerfile-debian10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:buster .

build_dsid:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build --rm -f Dockerfile-debiansid -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:sid -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:unstable .

push_dsid:
 stage: push
 only:
   - master
 script:
   - docker build --rm -f Dockerfile-debiansid -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:sid -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:unstable .
   - docker images
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:sid
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:unstable

push_d10:
 stage: push
 only:
   - master
 script:
   - docker build --rm -f Dockerfile-debian10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:buster -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest .
   - docker images
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:10
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:buster
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest