---
services: docker

env:
  global:
    - DOCKER_USER: qwe1
    - DOCKER_IMAGE: shellcheck
  matrix:
    - DOCKER_FILE: Dockerfile-debiansid
    - DOCKER_FILE: Dockerfile-debian10
  #matrix:
  #  - whatever

before_script:
  - docker info

script:
  - docker build -f $DOCKER_FILE -t $DOCKER_USER/$DOCKER_IMAGE:travis-$DOCKER_FILE .
  - docker images
  - docker run --rm $DOCKER_USER/$DOCKER_IMAGE:travis-$DOCKER_FILE cat /etc/os-release
  - docker run --rm $DOCKER_USER/$DOCKER_IMAGE:buster shellcheck --version
  - docker run --rm $DOCKER_USER/$DOCKER_IMAGE:sid shellcheck --version
