FROM debian:sid-slim
LABEL maintainer="Richard Skumat"

ENV DEBIAN_FRONTEND noninteractive

# Install dependencies.
RUN apt-get update \
    && apt-get install -y --no-install-recommends shellcheck \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
RUN useradd -m -s /bin/bash user
USER user